[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sonify-synth"
version = "0.1.0"
dependencies = ["numpy", "scipy"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["sonify_synth*"]  # Note the underscore here!
namespaces = false